/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.praktikumadpl_kedaikopigui.container;

/**
 *
 * @author Abe.dann
 */
public class FramePesanDialog extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FramePesanDialog.class.getName());

    /**
     * Creates new form FramePesanDialog
     */
    public FramePesanDialog() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DialogKonfirmasi = new javax.swing.JDialog();
        lblPesan = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnPesan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        DialogKonfirmasi.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        DialogKonfirmasi.setTitle("konfirmasi");
        DialogKonfirmasi.setModal(true);

        lblPesan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPesan.setText("Pesanan Anda Sudah Diterima, Terima Kasih");

        btnOK.setText("OK");
        btnOK.addActionListener(this::btnOKActionPerformed);

        javax.swing.GroupLayout DialogKonfirmasiLayout = new javax.swing.GroupLayout(DialogKonfirmasi.getContentPane());
        DialogKonfirmasi.getContentPane().setLayout(DialogKonfirmasiLayout);
        DialogKonfirmasiLayout.setHorizontalGroup(
            DialogKonfirmasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogKonfirmasiLayout.createSequentialGroup()
                .addGroup(DialogKonfirmasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DialogKonfirmasiLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(lblPesan))
                    .addGroup(DialogKonfirmasiLayout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(btnOK)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        DialogKonfirmasiLayout.setVerticalGroup(
            DialogKonfirmasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogKonfirmasiLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(lblPesan)
                .addGap(18, 18, 18)
                .addComponent(btnOK)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KedaiKopi-Pesan");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Americano - Rp. 20.000");

        btnPesan.setText("Pesan");
        btnPesan.addActionListener(this::btnPesanActionPerformed);

        jLabel2.setText("TEL-U COFFEE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(btnPesan))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel2)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(59, 59, 59)
                .addComponent(btnPesan)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesanActionPerformed
        // TODO add your handling code here:
        DialogKonfirmasi.pack();
        DialogKonfirmasi.setLocationRelativeTo(this);
        DialogKonfirmasi.setVisible(true);
    }//GEN-LAST:event_btnPesanActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        DialogKonfirmasi.dispose();
    }//GEN-LAST:event_btnOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FramePesanDialog().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog DialogKonfirmasi;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnPesan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblPesan;
    // End of variables declaration//GEN-END:variables
}
