/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.praktikumadpl_kedaikopigui.layout;

import javax.swing.JOptionPane;

/**
 *
 * @author Abe.dann
 */
public class CardLayoutPesan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CardLayoutPesan.class.getName());

    /**
     * Creates new form CardLayoutPesan
     */
    public CardLayoutPesan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pPilih = new javax.swing.JPanel();
        lblLangkah = new javax.swing.JLabel();
        lblNamaKopi = new javax.swing.JLabel();
        tfKopi = new javax.swing.JTextField();
        btnLanjut = new javax.swing.JButton();
        pKonfirmasi = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblPesanan = new javax.swing.JLabel();
        btnSelesai = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        lblLangkah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLangkah.setText("Langkah 1 dari 2 - Pilih Kopi");

        lblNamaKopi.setText("Nama Kopi:");

        btnLanjut.setText("Lanjut");
        btnLanjut.addActionListener(this::btnLanjutActionPerformed);

        javax.swing.GroupLayout pPilihLayout = new javax.swing.GroupLayout(pPilih);
        pPilih.setLayout(pPilihLayout);
        pPilihLayout.setHorizontalGroup(
            pPilihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPilihLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pPilihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pPilihLayout.createSequentialGroup()
                        .addComponent(lblLangkah)
                        .addGap(0, 199, Short.MAX_VALUE))
                    .addGroup(pPilihLayout.createSequentialGroup()
                        .addComponent(lblNamaKopi)
                        .addGap(18, 18, 18)
                        .addComponent(tfKopi))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pPilihLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnLanjut)))
                .addContainerGap())
        );
        pPilihLayout.setVerticalGroup(
            pPilihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPilihLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLangkah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pPilihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaKopi)
                    .addComponent(tfKopi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE)
                .addComponent(btnLanjut)
                .addContainerGap())
        );

        getContentPane().add(pPilih, "Pilih");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Langkah 2 dari 2 - Konfirmasi");

        lblPesanan.setText("Kopi yang dipilih:");

        btnSelesai.setText("Selesai");
        btnSelesai.addActionListener(this::btnSelesaiActionPerformed);

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(this::btnKembaliActionPerformed);

        javax.swing.GroupLayout pKonfirmasiLayout = new javax.swing.GroupLayout(pKonfirmasi);
        pKonfirmasi.setLayout(pKonfirmasiLayout);
        pKonfirmasiLayout.setHorizontalGroup(
            pKonfirmasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pKonfirmasiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pKonfirmasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblPesanan))
                .addContainerGap(197, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pKonfirmasiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKembali)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSelesai)
                .addContainerGap())
        );
        pKonfirmasiLayout.setVerticalGroup(
            pKonfirmasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pKonfirmasiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPesanan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                .addGroup(pKonfirmasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelesai)
                    .addComponent(btnKembali))
                .addContainerGap())
        );

        getContentPane().add(pKonfirmasi, "Konfirmasi");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLanjutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanjutActionPerformed
        // TODO add your handling code here:
        lblPesanan.setText("Kopi Yang Dipilih: " + tfKopi.getText());
        java.awt.CardLayout cl = (java.awt.CardLayout) getContentPane().getLayout();
        cl.show(getContentPane(), "Konfirmasi");
    }//GEN-LAST:event_btnLanjutActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        java.awt.CardLayout cl = (java.awt.CardLayout) getContentPane().getLayout();
        cl.show(getContentPane(), "Pilih");
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelesaiActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(this, "PESANAN SELESAI");
    }//GEN-LAST:event_btnSelesaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CardLayoutPesan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnLanjut;
    private javax.swing.JButton btnSelesai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblLangkah;
    private javax.swing.JLabel lblNamaKopi;
    private javax.swing.JLabel lblPesanan;
    private javax.swing.JPanel pKonfirmasi;
    private javax.swing.JPanel pPilih;
    private javax.swing.JTextField tfKopi;
    // End of variables declaration//GEN-END:variables
}
