/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.praktikumadpl_kedaikopigui.layout;

/**
 *
 * @author Abe.dann
 */
public class FlowLayout extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FlowLayout.class.getName());

    /**
     * Creates new form FlowLayout
     */
    public FlowLayout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTambahan = new javax.swing.JLabel();
        btnOat = new javax.swing.JButton();
        btnExtra = new javax.swing.JButton();
        btnEs = new javax.swing.JButton();
        btnSirup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());

        lblTambahan.setText("Pilih Tambahan");
        getContentPane().add(lblTambahan);

        btnOat.setText("susu oat");
        getContentPane().add(btnOat);

        btnExtra.setText("extra shot");
        getContentPane().add(btnExtra);

        btnEs.setText("es batu");
        getContentPane().add(btnEs);

        btnSirup.setText("sirup karamel");
        getContentPane().add(btnSirup);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FlowLayout().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEs;
    private javax.swing.JButton btnExtra;
    private javax.swing.JButton btnOat;
    private javax.swing.JButton btnSirup;
    private javax.swing.JLabel lblTambahan;
    // End of variables declaration//GEN-END:variables
}
